version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=canal_user
      - RABBITMQ_DEFAULT_PASS=canal_mdp
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq

volumes:
  rabbit-lfbaggr: